# Generated by Django 4.2.1 on 2023-06-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0044_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeDetails',
        ),
    ]
